# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 320d61e0ff1af2813f0976c4d2bff6ccfb7a392782201759794964f8bf744beefa04baa5e24dc32197284228bacb1861a9136fd728bffce6551f48942ca4d6c7

test:
  secret_key_base: b198bf2e5bee697fc90ebdf0720154e97cd9d4a289a13a30ff3b3e2d71df89b372ea734cf7e49ef021960e7bdc91138e6146ed3b051615f4c4f398a71b78d22f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
